version: "3"

services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: realmdbroot
      MONGO_INITDB_ROOT_PASSWORD: realmdbrootpassword
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - api

  api:
    container_name: api
    build: ./packages/api
    restart: always
    ports:
      - 3000:3000
    networks:
      - api
    depends_on:
      - database

  app:
    container_name: app
    build: ./packages/app
    restart: always
    ports:
      - 8080:80
    networks:
      - app
    depends_on:
      - api

volumes:
  data:

networks:
  api:
  app:
